name: Trigger Jenkins CI/CD

on:
  push:
    branches:
      - main

jobs:

  trigger-jenkins:

    runs-on: ubuntu-latest

    steps:

      - name: Trigger Jenkins Build
        run: |
          curl -X POST \
          "http://3.90.184.224:8080/job/DatingApp/build"
